### ISSUE TITLE
Verify connectivity from proxy w/ custom domain

### ISSUE THREAD

**Issue by Tulincarchta** [NezumiOrg/nezumiorg.github.io#10]

**Comment by MASintemaartensdijk** [comment]
Setting a new CNAME cannot be performed on a protected (`master`) branch. Branch was unprotected to set the custom domain. Requests are automatically transferred to www.nezumi.org.

**Comment by MASintemaartensdijk** [comment]
Having <https://nezumiorg.github.io> redirect and resolve to <https://www.nezumi.org> immediately, renders it useless as reference from the proxy behind <http://www.nezumi.org>. The proxy would simply loop to itself perpetually.
